---
- name: setting distro fact
  set_fact:
    distro: "{{ ansible_os_family }}-{{ linux_ad_ansible_distribution_major_version }}"
  when: ansible_os_family != 'Debian'
  tags:
    - aad_adjoin
    - aad_sssd
    - always

- name: setting distro fact
  set_fact:
    distro: "{{ ansible_os_distribution }}-{{ linux_ad_ansible_distribution_major_version }}"
  when: ansible_os_family == 'Debian'
  tags:
    - aad_adjoin
    - aad_sssd
    - always

# load version-specific variables
- name: include vars
  block:
    - include_vars: "{{ item }}"
      with_first_found:
        - "../vars/{{distro}}.yml"
  rescue:
    - fail: msg="Variables file for distro {{ distro }} were not found."
  tags:
    - aad_adjoin
    - aad_sssd

- import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: sshd.yml

- import_tasks: common.yml

- import_tasks: sudoers.yml

- meta: flush_handlers

# - name: Update sudoers to give AD group access
#   lineinfile:
#     path: /etc/sudoers
#     state: present
#     regexp: '^%domain\s'
#     line: '%domain\ admins@cloud.statcan.ca'

- name: create Active Directory home directory
  file:
    path: '{{ item }}'
    owner: '{{ linux_ad_home_dir_user }}'
    group: '{{ linux_ad_home_dir_group }}'
    mode: '{{ linux_ad_home_dir_mode }}'
    recurse: yes
    state: directory
  with_items: '{{ linux_ad_home_dir_base | default([]) }}'
