---
- name: auth packages
  apt:
    name: "{{ authconfig_packages }}"
    update_cache: true
  tags:
    - aad_agent
    - aad_packages
    - aad_sssd

- name: remove packages not required auth packages
  apt:
    name: '{{ authconfig_remove_packages }}'
    state: absent
  tags:
    - aad_agent
    - aad_packages_remove
    - aad_sssd

- name: /etc/hosts entry
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.{{ linux_ad_authconfig_domain }} {{ ansible_hostname }}"

- name: smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - "restart smbd"
    - "disable nmbd"
    - "restart winbind"
  tags:
    - aad_smb_conf
    - aad_samba

- name: discover Domain
  shell:
    cmd: "realm discover -v {{ linux_ad_authconfig_domain }}"

- name: list realms
  shell:
    cmd: "realm list"

- name: join Domain (net ads)
  shell:
    cmd: "echo -n '{{ linux_ad_authconfig_sssd_pass }}' | net ads join -D {{ linux_ad_authconfig_domain }} -U {{ linux_ad_authconfig_sssd_user }}"
    creates: /etc/krb5.keytab
  become: yes
  notify:
    - "restart chrony"
    - "restart smbd"
    - "disable nmbd"
    - "restart winbind"
    - "restart sssd"
  tags:
    - aad_adjoin
    - aad_agent
    - aad_samba
  when linux_ad_join_method == 'netads'


- name: join Domain (realm)
  shell:
    cmd: "echo -n '{{ linux_ad_authconfig_sssd_pass }}' | realm join --computer-ou='{{ linux_ad_authconfig_computer_ou }}' login-user='{{ linux_ad_authconfig_sssd_user }}' '{{ linux_ad_authconfig_domain }}''"
    creates: /etc/krb5.keytab
  become: yes
  notify:
    - "restart chrony"
    - "restart smbd"
    - "disable nmbd"
    - "restart winbind"
    - "restart sssd"
  tags:
    - aad_adjoin
    - aad_agent
    - aad_samba
  when linux_ad_join_method == 'realm'

- name: join Domain (adcli)
  shell:
    cmd: "echo -n '{{ linux_ad_authconfig_sssd_pass }}' | adcli join --stdin-password --host-fqdn='{{ ansible_hostname }}.{{ linux_ad_authconfig_domain }}' --domain-ou='{{ linux_ad_authconfig_computer_ou }}' --login-user={{ linux_ad_authconfig_sssd_user }} -S  {{ linux_ad_ad_info_ad_server }} {{ linux_ad_authconfig_domain }}"
    creates: /etc/krb5.keytab
  become: yes
  notify:
    - "restart chrony"
    - "restart smbd"
    - "disable nmbd"
    - "restart winbind"
    - "restart sssd"
  tags:
    - aad_adjoin
    - aad_agent
    - aad_samba
  when linux_ad_join_method == 'adcli'

- name: add mkhomedir to common-session
  lineinfile:
    dest: /etc/pam.d/common-session
    line: 'session required        pam_mkhomedir.so skel=/etc/skel/ umask=0027'
    regexp: '.*pam_mkhomedir\.so.*'
    insertafter: '.*pam_unix\.so.*'
  tags:
    - aad_pam
    - aad_home

- name: nsswitch passwd
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'passwd:         compat systemd sss'
    regexp: '^passwd: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch shadow
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'shadow:         compat sss'
    regexp: '^shadow: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch group
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'group:          compat systemd sss'
    regexp: '^group: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch netgroup
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'netgroup:       nis sss'
    regexp: '^netgroup: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: join Samba to the Domain
  shell:
    cmd: "net ads join -k"
  notify:
    - "restart smbd"
    - "disable nmbd"
    - "restart winbind"

  tags:
    - aad_adjoin
    - aad_agent
    - aad_samba
