---
- name: auth packages
  apt:
    name: "{{ authconfig_packages }}"
    update_cache: true

- name: nsswitch passwd
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'passwd:         compat systemd sss'
    regexp: '^passwd: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch shadow
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'shadow:         compat sss'
    regexp: '^shadow: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch group
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'group:          compat systemd sss'
    regexp: '^group: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch netgroup
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'netgroup:       nis sss'
    regexp: '^netgroup: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: /etc/hosts entry
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }}  {{ ansible_hostname }}.{{ linux_ad_authconfig_domain }} {{ ansible_hostname }}"


# PAM module to auto-create home directories
- name: mkhomedir
  template:
    dest: '/usr/share/pam-configs/mkhomedir'
    src: 'mkhomedir.j2'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: pam-auth-update

# PAM module to restrict access to specific users/groups
#- name: enable access restrictions
#  template:
#    dest: /usr/share/pam-configs/access
#    src: pam_config_access.j2
#    owner: 'root'
#    group: 'root'
#    mode: 0644
#  notify: pam-auth-update
