---
- name: auth packages
  apt:
    name: "{{ authconfig_packages }}"
    update_cache: true

- name: smb.conf
  template:
    src: smb.conf.j2
    dest: /etc/samba/krb5.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - aad_smb_conf
    - aad_samba

- name: login to Domain
  shell: "echo -n '{{ linux_ad_authconfig_sssd_pass }}' | kinit {{ linux_ad_authconfig_sssd_user }}"
  args:
    creates: /etc/krb5.keytab
  tags:
    - aad_adlogin
    - aad_agent
    - aad_samba

- name: join Domain
  shell: "net ads join -k"
  notify:
    - "restart chrony"
    - "restart smbd"
    - "restart nmbd"
    - "restart sssd"
  tags:
    - aad_adjoin
    - aad_agent
    - aad_samba

- name: nsswitch passwd
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'passwd:         compat systemd sss'
    regexp: '^passwd: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch shadow
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'shadow:         compat sss'
    regexp: '^shadow: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch group
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'group:          compat systemd sss'
    regexp: '^group: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: nsswitch netgroup
  lineinfile:
    dest: /etc/nsswitch.conf
    line: 'netgroup:       nis sss'
    regexp: '^netgroup: .*'
  tags:
    - aad_nsswitch
    - aad_sssd

- name: /etc/hosts entry
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }}  {{ ansible_hostname }}.{{ linux_ad_authconfig_domain }} {{ ansible_hostname }}"
